#[en]
#  LanguageName = "English"
#  weight = 1
# [tr]
#   LanguageName = "Turkish"
#   weight = 1

[en]
  locale = 'en'
  label = 'English'
  weight = 1

  [en.permalinks]
    blog = '/blog/:contentbasename/'

[ru]
  contentDir = 'ru'
  label = 'Русский'
  weight = 2

  [ru.permalinks]
    blog = '/blogs/:contentbasename/'