[[shortcuts]]
  name = "<i class='fa-brands fa-discord'></i> Daisy's Discord"
  url = 'https://discord.gg/fxhXWgxcHV'
  weight = 10

[[shortcuts]]
  identifier = 'ds'
  name = "<i class='fa-fw fab fa-github'></i> GitHub repo"
  url = 'https://github.com/doodlebunnyhops/doodlebunnyhops.github.io'
  weight = 11

[[shortcuts]]
  name = "<i class='fa-brands fa-x-twitter'></i> Twitter/X"
  url = 'https://x.com/SolveBHMystery'
  weight = 12

[[shortcuts]]
  name = "<i class='fa-brands fa-square-reddit'></i> Reddit"
  url = 'https://www.reddit.com/r/BrookhavenRPSecrets/'
  weight = 13

[[main]]
  name = "Blog"
  weight = 5
  url = "blog/"