baseURL = "https://solve.bhmystery.com/"
title = "Brookhaven Secrets and Mysteries"
enableRobotsTXT = true

# this example loads the theme as hugo module
# comment out line below, and uncomment the line after it if you prefer to load the theme normally
#theme = ["github.com/onweru/compose"] # edit this if you'ld rather use a fork of this repo
 theme = ["compose","reveal-hugo"]
enableGitInfo = true
enableEmoji = true
canonifyURLs = true

paginate = 40

googleAnalytics = 'G-LYV1YN0FYF'

disableKinds = ['taxonomy', 'term']
#disableKinds = ["sitemap"]
#[sitemap]
#  filename = "content/sitemap.xml"

[outputs]
  home = ["HTML", "RSS","JSON"]
  
#[markup.goldmark.renderer]
[markup]
  [markup.goldmark]
    duplicateResourceFiles = false
    [markup.goldmark.extensions]
      #table = false
#unsafe = false

[outputFormats.Reveal]
baseName = "reveal"
mediaType = "text/html"
isHTML = true

twitter = "@SolveBHMystery"
largeTwitterCard = true

[author]
  name = "Bloomindaisy"

  numberOfTagsShown = 5

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true