baseURL: 'https://doodlebunnyhops.github.io/'
languageCode: en-us
title: The Unoffical Guide
theme: compose
enableRobotsTXT: true
enableGitInfo: true
disableKinds:
- sitemap


outputs:
  home:
    - HTML
    - RSS
    - JSON
# contentDir: "content"
# menu:
  # main:
  # - name: Guide
    # pageRef: /guide
    # weight: 20
  # - name: About
    # pageRef: /about
    # weight: 30