baseURL = "https://solve.bhmystery.com/testsite/"
enableRobotsTXT = true
relativeURLs = true

timeout = "60s"

# this example loads the theme as hugo module
# comment out line below, and uncomment the line after it if you prefer to load the theme normally
#theme = ["github.com/onweru/compose"] # edit this if you'ld rather use a fork of this repo
# theme = ["compose","reveal-hugo"]
theme = ["hugo-theme-relearn"]
enableGitInfo = true
enableEmoji = true
# canonifyURLs = true
showVisitedLinks = false
disableTagHiddenPages = true
disableTermBreadcrumbs = true


[pagination]
  pagerSize = 40


[services]
  [services.googleAnalytics]
    ID = 'G-LYV1YN0FYF'
  [services.disqus]
    shortname = 'brookhaven-mystery'

disableKinds = ['taxonomy', 'term', 'category','tag']
#disableKinds = ["sitemap"]

[outputs]
  home = ["HTML", "RSS"]
  page = ['html', 'rss', 'print']
  section = ['html', 'rss']
  
[markup]
  [markup.goldmark]
    duplicateResourceFiles = false
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      [markup.goldmark.extensions.cjk]
        eastAsianLineBreaks = false
        eastAsianLineBreaksStyle = 'simple'
        enable = false
        escapedSpace = false
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.delete]
          enable = false
        [markup.goldmark.extensions.extras.insert]
          enable = false
        [markup.goldmark.extensions.extras.mark]
          enable = true
        [markup.goldmark.extensions.extras.subscript]
          enable = false
        [markup.goldmark.extensions.extras.superscript]
          enable = false
      [markup.goldmark.extensions.passthrough]
        enable = false
        [markup.goldmark.extensions.passthrough.delimiters]
          block = []
          inline = []
      [markup.goldmark.extensions.typographer]
        apostrophe = '&rsquo;'
        disable = false
        ellipsis = '&hellip;'
        emDash = '&mdash;'
        enDash = '&ndash;'
        leftAngleQuote = '&laquo;'
        leftDoubleQuote = '&ldquo;'
        leftSingleQuote = '&lsquo;'
        rightAngleQuote = '&raquo;'
        rightDoubleQuote = '&rdquo;'
        rightSingleQuote = '&rsquo;'
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      wrapStandAloneImageWithinParagraph = true
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = false
      [markup.goldmark.renderHooks.link]
        enableDefault = false
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false

[outputFormats.Reveal]
baseName = "reveal"
mediaType = "text/html"
isHTML = true

twitter = "@SolveBHMystery"
largeTwitterCard = true

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[params]
  disableAssetsBusting = false
  collapsibleMenu=true
  alwaysopen=false

  [[params.themeVariant]]
    identifier = 'my-dark'
    name = 'Dark'
  
#  [[params.themeVariant]]
#    identifier = 'my-light'
#    name = 'Light'

  [params.imageEffects]
    border = false
    lazy = true
    lightbox = true
    shadow = false


copyright = '2023'
[params.author]
  name = 'BloominDaisy'
  email = 'daisy@bhmystery.com'


#defaultContentLanguage = 'en'
