baseURL = "http://bh.local:1313/"
title = "Brookhaven Secrets and Mysteries"
enableRobotsTXT = true
# this example loads the theme as hugo module
# comment out line below, and uncomment the line after it if you prefer to load the theme normally
#theme = ["github.com/onweru/compose"] # edit this if you'ld rather use a fork of this repo
 theme = ["compose","reveal-hugo"]
enableGitInfo = true
enableCopyright = true

# disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "RSS","JSON"]
  
[markup.goldmark.renderer]
unsafe = false

[outputFormats.Reveal]
baseName = "reveal"
mediaType = "text/html"
isHTML = true